### ISSUE TITLE
[helm] document how to add database

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/superset#8]
Document how to add a DB config at deployment time, on helm chart.

Should be fairly consistent with https://github.com/apache/superset/blob/master/helm/superset/values.yaml#L111, but I noticed that exported DB config is slightly different, e.g.: 

```
database_name: gis
sqlalchemy_uri: postgresql+psycopg2://superset:XXXXXXXXXX@postgres_host:5432/mydb
cache_timeout: null
expose_in_sqllab: true
allow_run_async: false
allow_ctas: false
allow_cvas: false
allow_dml: false
allow_csv_upload: false
extra:
  allows_virtual_table_explore: true
  metadata_params: {}
  engine_params: {}
  metadata_cache_timeout: {}
  schemas_allowed_for_csv_upload: []
impersonate_user: false
uuid: cab2045e-f58a-4453-bb80-fb97b28cd9ef
version: 1.0.0

```
